using System;
using System.Collections.Generic;
using System.Linq;
using BankingManagmentSystem.Entities;
using BankingManagmentSystem.Services;

namespace BankingManagmentSystem
{
	public class DemoDataProvider
	{
		public int UserCount { get; } = 1000;
		private List<string> lastNames = new List<string>
				{
					"Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez","Lopez",
					"Gonzales","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin",
					"Lee",
					"Perez",
					"Thompson",
					"White",
					"Harris",
					"Sanchez",
					"Clark",
					"Ramirez",
					"Lewis",
					"Robinson",
					"Walker",
					"Young",
					"Allen",
					"King",
					"Wright",
					"Scott",
					"Torres",
					"Nguyen",
					"Hill",
					"Flores",
					"Green",
					"Adams",
					"Nelson",
					"Baker",
					"Hall",
					"Rivera",
					"Campbell",
					"Mitchell",
					"Carter",
					"Roberts",
					"Gomez",
					"Phillips",
					"Evans",
					"Turner",
					"Diaz",
					"Parker",
					"Cruz",
					"Edwards",
					"Collins",
					"Reyes",
					"Stewart",
					"Morris",
					"Morales",
					"Murphy",
					"Cook",
					"Rogers",
					"Gutierrez",
					"Ortiz",
					"Morgan",
					"Cooper",
					"Peterson",
					"Bailey",
					"Reed",
					"Kelly",
					"Howard",
					"Ramos",
					"Kim",
					"Cox",
					"Ward",
					"Richardson",
					"Watson",
					"Brooks",
					"Chavez",
					"Wood",
					"James",
					"Bennet",
					"Gray",
					"Mendoza",
					"Ruiz",
					"Hughes",
					"Price",
					"Alvarez",
					"Castillo",
					"Sanders",
					"Patel",
					"Myers",
					"Long",
					"Ross",
					"Foster",
					"Jimenez"
				};
		private List<string> maleFirstNames = new List<string>
				{
					"James",
					"Robert",
					"John",
					"Michael",
					"David",
					"William",
					"Richard",
					"Joseph",
					"Thomas",
					"Charles",
					"Christopher",
					"Daniel",
					"Matthew",
					"Anthony",
					"Mark",
					"Donald",
					"Steven",
					"Paul",
					"Andrew",
					"Joshua",
					"Kenneth",
					"Kevin",
					"Brian",
					"George",
					"Timothy",
					"Ronald",
					"Edward",
					"Jason",
					"Jeffrey",
					"Ryan",
					"Jacob",
					"Gary",
					"Nicholas",
					"Eric",
					"Jonathan",
					"Stephen",
					"Larry",
					"Justin",
					"Scott",
					"Brandon",
					"Benjamin",
					"Samuel",
					"Gregory",
					"Alexander",
					"Frank",
					"Patrick",
					"Raymond",
					"Jack",
					"Dennis",
					"Jerry",
					"Tyler",
					"Aaron",
					"Jose",
					"Adam",
					"Nathan",
					"Henry",
					"Douglas",
					"Zachary",
					"Peter",
					"Kyle",
					"Ethan",
					"Walter",
					"Noah",
					"Jeremy",
					"Christian",
					"Keith",
					"Roger",
					"Terry",
					"Gerald",
					"Harold",
					"Sean",
					"Austin",
					"Carl",
					"Arthur",
					"Lawrence",
					"Dylan",
					"Jesse",
					"Jordan",
					"Bryan",
					"Billy",
					"Joe",
					"Bruce",
					"Gabriel",
					"Logan",
					"Albert",
					"Willie",
					"Alan",
					"Juan",
					"Wayne",
					"Elijah",
					"Randy",
					"Roy",
					"Vincent",
					"Ralph",
					"Eugene",
					"Russell",
					"Bobby",
					"Mason",
					"Philip",
					"Louis"
				};
		private List<string> femaleFirstName = new List<string>
				{
					"Mary",
					"Patricia",
					"Jennifer",
					"Linda",
					"Elizabeth",
					"Barbara",
					"Susan",
					"Jessica",
					"Sarah",
					"Karen",
					"Lisa",
					"Nancy",
					"Betty",
					"Margaret",
					"Sandra",
					"Ashley",
					"Kimberly",
					"Emily",
					"Donna",
					"Michelle",
					"Carol",
					"Amanda",
					"Dorothy",
					"Melissa",
					"Deborah",
					"Stephanie",
					"Rebecca",
					"Sharon",
					"Laura",
					"Cynthia",
					"Kathleen",
					"Amy",
					"Angela",
					"Shirley",
					"Anna",
					"Brenda",
					"Pamela",
					"Emma",
					"Nicole",
					"Helen",
					"Samantha",
					"Katherine",
					"Christine",
					"Debra",
					"Rachel",
					"Carolyn",
					"Janet",
					"Catherine",
					"Maria",
					"Heather",
					"Diane",
					"Ruth",
					"Julie",
					"Olivia",
					"Joyce",
					"Virginia",
					"Victoria",
					"Kelly",
					"Lauren",
					"Christina",
					"Joan",
					"Evelyn",
					"Judith",
					"Megan",
					"Andrea",
					"Cheryl",
					"Hannah",
					"Jacqueline",
					"Martha",
					"Gloria",
					"Teresa",
					"Ann",
					"Sara",
					"Madison",
					"Frances",
					"Kathryn",
					"Janice",
					"Jean",
					"Abigail",
					"Alice",
					"Julia",
					"Judy",
					"Sophia",
					"Grace",
					"Denise",
					"Amber",
					"Doris",
					"Marilyn",
					"Danielle",
					"Beverly",
					"Isabella",
					"Theresa",
					"Diana",
					"Natalie",
					"Brittany",
					"Charlotte",
					"Marie",
					"Kayla",
					"Alexis",
					"Lori",
				};
		

		private ICryptographyService cryptographyService = new CryptographyService();

		public IEnumerable<BmcUser> Fake1000Users()
		{
			var userList = new Dictionary<string, BmcUser>();
			var random = new Random();
			var maleOrFemale = true;
			int guidPointer = 0;
			while (userList.Count < UserCount)
			{
				var lastNamePointer = random.Next(lastNames.Count());
				int namePointer;
				if (maleOrFemale)
				{
					namePointer = random.Next(maleFirstNames.Count());
				}
				else
				{
					namePointer = random.Next(femaleFirstName.Count());
			    }
				var lastName = lastNames[lastNamePointer];
				var firstName = maleOrFemale ? maleFirstNames[namePointer] : femaleFirstName[namePointer];
				var userName = $"{firstName} {lastName}";

				var user = new BmcUser
				{
					Id = Guid.NewGuid(),
					UserName = userName,
					Email = $"{firstName}_{lastName}@irocbank.com",
					NormalizedEmail = $"{firstName}_{lastName}@irocbank.com".ToUpperInvariant(),
					PasswordHash = cryptographyService.GetPasswordHash(Guid.NewGuid().ToString()),
					SecurityStamp = Guid.NewGuid().ToString(),
					TwoFactorEnabled = false
				};
				if (userList.TryAdd(userName, user))
				{
					maleOrFemale = !maleOrFemale;
					guidPointer++;
				}
			}

			return userList.Values;
		}

		public BmcUser GetSystemAdmin()
		{
			return new BmcUser
            {
                Id = new Guid("779f3783-e69a-4265-b92f-188943ed3be8"),
                UserName = "Admin",
                Email = $"admin@irocbank.com",
                NormalizedEmail = $"admin@irocbank.com".ToUpperInvariant(),
                PasswordHash = cryptographyService.GetPasswordHash("admin"),
                SecurityStamp = Guid.NewGuid().ToString(),
                TwoFactorEnabled = false
            };
        }
	}
}